### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by yxxyun** [codedot/xmm#1]
Task statement: provides documentation on market maker, market taker, and statistics.

**Comment by codedot** [comment]
Task statement: provides documentation on market maker, market taker, and statistics.

**Comment by codedot** [comment]
A new RippleAPI-based version of XMM is being developed from scratch (currently, on an orphan branch named `ng`) in the form of a Node.js package with both CLI and API. The new package provides up-to-date documentation which is available in the NPM repository through the following address:

https://www.npmjs.com/package/xmm
